# Generated by Django 6.0.2 on 2026-02-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_migrate_teacher_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
